### ISSUE TITLE
Explanation Python implementation

### ISSUE THREAD

**Issue by DonaldTsang** [cloudflare/sidh#23]
I have found that ECC and NTRU has pure python (no numpy) implementations but there is none for SIDH, is it possible to write one for demonstrating SIDH?
- NTRUEncrypt  (https://github.com/logannc/pyNTRUEncrypt),
- ECC (https://github.com/johndoe31415/joeecc)

**Comment by henrydcase** [comment]
Hi,

Yes, it's actually quite easy. Please allow me few days

**Comment by henrydcase** [comment]
Here you go:
https://gitlab.cs.hs-rm.de/pqcrypto/SIDH.git

**Comment by DonaldTsang** [comment]
@henrydcase Thanks! Is it possible to mirror it in Github as well?
