### ISSUE TITLE
Adding p964 support? Please?

### ISSUE THREAD

**Issue by mouse07410** [cloudflare/sidh#25]
Could you please add support for SIDH on P964? For those who'd like to have symmetric strength equivalent of AES-256?

Thank you!

**Comment by henrydcase** [comment]
Why not. Is there any project you would use it for?

**Comment by henrydcase** [comment]
So,
* There are some constructions allowing using AKE with SIDH (see this for example: https://eprint.iacr.org/2018/266.pdf)
* I'm working on cSIDH which is definitely more experimental than SIDH, but it is also an algorithm which would allow you doing something like this https://signal.org/docs/specifications/x3dh/x3dh.pdf. But again - that's at very experimental stage
* This calling Go from C stuff is possible with CGo. Nevertheless, I've never tried it and heard that cgo may be problematic. But - there is C implementation of SIDH from Microsoft here https://github.com/Microsoft/PQCrypto-SIDH. I think it also doesn't have P964 implemented, but maybe doing development there makes more sense.

Is this project of yours which requires quantum-resistant KEX something open source? I give better advice if I know what's the use case.

**Comment by mouse07410** [comment]
Thank you for the pointers - I'll track them down.

I'm aware of cSIDH and am in contact with the authors, thanks.

I know the MS SIDH C implementation - and it's very reasonable one, but MS thinks that "you don't need security level higher than p751 provides" (of course

**Comment by henrydcase** [comment]
> I'm not sure how difficult it's likely to be to port p964 from a SIKE implementation to SIDH.

It's not difficult at all. Doing it fast is maybe more difficult and I may be doing it in C at some point.

**Comment by mouse07410** [comment]
> > I'm not sure how difficult it's likely to be to port p964 from a SIKE implementation to SIDH.
>
> It's not difficult at all. Doing it fast is maybe more difficult and I may be doing it in C at some point.

I'd love to lay my hands on the results of the above.

Do you happen to know if anybody implemented any of these https://eprint.iacr.org/2018/266.pdf proposals?

**Comment by henrydcase** [comment]
Will let you know once ready.
I'm aware of 2018/266 but I'm not aware of any implementation.

**Comment by mouse07410** [comment]
> Will let you know once ready

Thank you!!

**Comment by kriskwiatkowski** [comment]
https://eprint.iacr.org/2019/298.pdf

So I guess implementing 964 doesn't make sense anymore. I'll rather update the code with smaller field sizes
